version: 2

# Define the jobs we want to run for this project
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: make all

# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
